import "WindowModel.idl";

namespace SnapLayout
{
    [default_interface]
    runtimeclass OverviewWindow : WinUI3Package.TransparentWindow
    {
        OverviewWindow();

        Windows.Foundation.Collections.IObservableVector<WindowModel> Windows{ get; };
        static Microsoft.UI.Xaml.Visibility ConvertIconToVisibility(Microsoft.UI.Xaml.Media.ImageSource icon);
    }
}
