namespace SnapLayout
{
    [bindable]
    [default_interface]
    runtimeclass ThumbnailVisualControl : Microsoft.UI.Xaml.Controls.Control
    {
        ThumbnailVisualControl();
        UInt64 Handle;
    }
}
