namespace SnapLayout
{
    [bindable]
    [default_interface]
    runtimeclass WindowModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        WindowModel(UInt64 handle);
	    Microsoft.UI.Xaml.Media.ImageSource Icon{ get; };
        UInt64 Handle{ get; };
        String Title{ get; };

        void Close();
    }
}
